# name: Build Signed Android App Bundle

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Decode keystore
#         run: |
#           echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > android/app/your-keystore.jks

#       - name: Set up environment variables
#         run: |
#           echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
#           echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
#           echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

# #
#       - name: Set up Java 11
#         uses: actions/setup-java@v2
#         with:
          # java-version: '11'
          # distribution: 'adopt'

      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
#         # with:
#         #   flutter-version: 'stable'  # Ensure you're using the stable channel

#       # - name: Flutter doctor
#       #   run: flutter doctor
        
#       # - name: Flutter clean
#       #   run: flutter clean

#       # - name: Flutter dependencies upgrade
#       #   run: flutter pub upgrade --major-versions

#       - name: Install Flutter dependencies
#         run: flutter pub get

#       - name: Build Android App Bundle
#         # env:
#         #   KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
#         #   KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
#         #   KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
#         #   ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/android/my-release-key.jks
#         run: flutter build appbundle --release

#       - name: Upload AAB
#         uses: actions/upload-artifact@v3
#         with:
#           name: android-app-bundle
#           path: build/app/outputs/bundle/release/app-release.aab

name: Build Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        # with:
        #   flutter-version: 'stable'

      - name: Decode keystore
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > android/app/your-keystore.jks

      - name: Set up environment variables
        run: |
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release --no-shrink

      # - name: Upload APK
      #   uses: actions/upload-artifact@v2
        # with:
        #   name: release-apk
        #   path: build/app/outputs/flutter-apk/app-release.apk
